// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Infrastructure;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260525164338_Data")]
    partial class Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Admissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientPesel")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientPesel");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdmissionDate = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DischargeDate = new DateTime(2026, 5, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "90010112345",
                            WardId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdmissionDate = new DateTime(2026, 5, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "85050567890",
                            WardId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdmissionDate = new DateTime(2026, 5, 6, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            DischargeDate = new DateTime(2026, 5, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "72031245678",
                            WardId = 3
                        },
                        new
                        {
                            Id = 4,
                            AdmissionDate = new DateTime(2026, 5, 8, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "04122098765",
                            WardId = 4
                        },
                        new
                        {
                            Id = 5,
                            AdmissionDate = new DateTime(2026, 5, 9, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "68111122233",
                            WardId = 5
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.BedAssignments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientPesel")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("PatientPesel");

                    b.ToTable("BadAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedId = 1,
                            From = new DateTime(2026, 5, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "90010112345",
                            To = new DateTime(2026, 5, 5, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BedId = 2,
                            From = new DateTime(2026, 5, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "85050567890"
                        },
                        new
                        {
                            Id = 3,
                            BedId = 3,
                            From = new DateTime(2026, 5, 6, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "72031245678",
                            To = new DateTime(2026, 5, 10, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BedId = 4,
                            From = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "04122098765"
                        },
                        new
                        {
                            Id = 5,
                            BedId = 5,
                            From = new DateTime(2026, 5, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientPesel = "68111122233"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.BedTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("BedTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Łóżko standardowe",
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Łóżko OIOM",
                            Name = "Intensywna terapia"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Łóżko rehabilitacyjne",
                            Name = "Rehabilitacyjne"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Łóżko pediatryczne",
                            Name = "Dziecięce"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Łóżko sterowane elektrycznie",
                            Name = "Elektryczne"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Beds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("BedTypeId");

                    b.HasIndex("RoomId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedTypeId = 1,
                            RoomId = "A101"
                        },
                        new
                        {
                            Id = 2,
                            BedTypeId = 2,
                            RoomId = "B201"
                        },
                        new
                        {
                            Id = 3,
                            BedTypeId = 3,
                            RoomId = "C301"
                        },
                        new
                        {
                            Id = 4,
                            BedTypeId = 4,
                            RoomId = "D401"
                        },
                        new
                        {
                            Id = 5,
                            BedTypeId = 5,
                            RoomId = "E501"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Patients", b =>
                {
                    b.Property<string>("Pesel")
                        .HasColumnType("char(11)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.HasKey("Pesel");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Pesel = "90010112345",
                            Age = 35,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            Sex = false
                        },
                        new
                        {
                            Pesel = "85050567890",
                            Age = 40,
                            FirstName = "Anna",
                            LastName = "Nowak",
                            Sex = true
                        },
                        new
                        {
                            Pesel = "72031245678",
                            Age = 53,
                            FirstName = "Piotr",
                            LastName = "Wiśniewski",
                            Sex = false
                        },
                        new
                        {
                            Pesel = "04122098765",
                            Age = 20,
                            FirstName = "Zuzanna",
                            LastName = "Kaczmarek",
                            Sex = true
                        },
                        new
                        {
                            Pesel = "68111122233",
                            Age = 57,
                            FirstName = "Marek",
                            LastName = "Lewandowski",
                            Sex = false
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Rooms", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(4)");

                    b.Property<bool>("HasTv")
                        .HasColumnType("bit");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WardId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = "A101",
                            HasTv = true,
                            WardId = 1
                        },
                        new
                        {
                            Id = "B201",
                            HasTv = true,
                            WardId = 2
                        },
                        new
                        {
                            Id = "C301",
                            HasTv = false,
                            WardId = 3
                        },
                        new
                        {
                            Id = "D401",
                            HasTv = true,
                            WardId = 4
                        },
                        new
                        {
                            Id = "E501",
                            HasTv = false,
                            WardId = 5
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Wards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Oddział chorób serca i układu krążenia",
                            Name = "Kardiologia"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Oddział chirurgii ogólnej",
                            Name = "Chirurgia"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Oddział leczenia urazów i schorzeń kości",
                            Name = "Ortopedia"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Oddział dziecięcy",
                            Name = "Pediatria"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Oddział chorób układu nerwowego",
                            Name = "Neurologia"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Admissions", b =>
                {
                    b.HasOne("WebApplication1.Models.Patients", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientPesel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Wards", "Ward")
                        .WithMany("Admissions")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("WebApplication1.Models.BedAssignments", b =>
                {
                    b.HasOne("WebApplication1.Models.Beds", "Bed")
                        .WithMany("BedAssignments")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Patients", "Patient")
                        .WithMany("BedAssignments")
                        .HasForeignKey("PatientPesel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApplication1.Models.Beds", b =>
                {
                    b.HasOne("WebApplication1.Models.BedTypes", "BedType")
                        .WithMany("Beds")
                        .HasForeignKey("BedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Rooms", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BedType");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WebApplication1.Models.Rooms", b =>
                {
                    b.HasOne("WebApplication1.Models.Wards", "ward")
                        .WithMany("Rooms")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ward");
                });

            modelBuilder.Entity("WebApplication1.Models.BedTypes", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("WebApplication1.Models.Beds", b =>
                {
                    b.Navigation("BedAssignments");
                });

            modelBuilder.Entity("WebApplication1.Models.Patients", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("BedAssignments");
                });

            modelBuilder.Entity("WebApplication1.Models.Rooms", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("WebApplication1.Models.Wards", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
